---

- hosts: all
  user: heathkh
  sudo: True  
  vars:
    psad_email: heathkh@gmail.com
    
  tasks:
    - name: install psad packages 
      apt: pkg=$item state=installed update_cache=yes
      with_items:
        - psad
        
    - name: Enable psad
      template: src=psad.conf.j2 dest=/etc/psad/psad.conf
      
    - name: config iptables for psad logging
      command: $item
      with_items:
        - iptables -A INPUT -j LOG
        - iptables -A FORWARD -j LOG
        - ip6tables -A INPUT -j LOG
        - ip6tables -A FORWARD -j LOG
        
    - name: reload psad
      command: psad -R
      
    - name: regenerate psad signature
      command: psad --sig-update
      
    - name: regenerate psad signature
      command: psad -H
      ignore_errors: True